name: DBT_GIT_INT
version: 1.0.0
config-version: 2
profile: DBT_GIT_INT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  starter_project:
    staging:
      +schema: LANDING
      +materialized: view
    marts:
      +schema: FINAL
      +materialized: table    
      +transient: false
